### ISSUE TITLE
Envoyer un événement calendrier par mail lors d'une résa

### ISSUE THREAD

**Issue by crazy-max** [lgangloff/crossfit-2.0#27]
Pourrait être utile lorsque l'on gère son agenda par téléphone ou autre d'envoyer un event calendar (mail) à l'adresse du membre.

**Comment by lgangloff** [comment]
Yes, je pensais implémenter un export de ses résas sous format ical.

**Comment by crazy-max** [comment]
J'sais pas ce que je fais mais je valide ton issue 😀
Oublie pas l'tempo xD

**Comment by lgangloff** [comment]
J'sais pas ce que tu fais non plus, mais ça me va !
