### ISSUE TITLE
[Carte] Réservation -30min / +2h non effectif

### ISSUE THREAD

**Issue by crazy-max** [lgangloff/crossfit-2.0#3]
J'ai testé de scanner une carte à 18h38 pour un créneau à 20h-21h et c'est passé alors que ça ne devrait pas suivant la règle mise en place -30min et +2h.

**Comment by lgangloff** [comment]
à 18h38, ça veut dire qu'on check si tu as une résa entre 18h08 et 20h38. Si t'as réservé pour le créneau de 20h, c'est dedans, non ?

**Comment by crazy-max** [comment]
Ah ok meaculpa j'pensais que la période c'était -30min / +2h mais c'est plutôt le contraire -2h / +30min ?

**Comment by lgangloff** [comment]
30minutes dans le passé et 2h dans le futur Marty McFly ;) 
Ces valeurs sont surchargeables avec les paramètres lessMinute & moreMinute :)

**Comment by crazy-max** [comment]
Ok donc si créneau à 20h ça veut dire que mon scan sera valide entre 19h30 et 22h ou bien entre 18h et 20h30 ?!?

**Comment by lgangloff** [comment]
C'est pas par rapport à l'heure du créneau. Mais par rapport à l'heure ou tu passes ta carte. 
Si tu la passe à 17h56, on cherche une résa pour un créneau entre 17h26 & 19h56 => Ca ne matchera pas.
Si tu la passe à 19h48, on cherche une résa pour un créneau entre 19h18 & 21h48 => Ca matchera.
Si tu la passe à 20h20, on cherche une résa pour un créneau entre 19h50 & 22h20 => Ca matchera.
Si tu la passe à 20h31, on cherche une résa pour un créneau entre 20h01 & 22h31 => Ca ne matchera pas.
