### ISSUE TITLE
Impossible d’accéder au planning (accueil admin)

### ISSUE THREAD

**Issue by guillaumecolin** [lgangloff/crossfit-2.0#32]
error:"Internal Server Error"
exception:"org.springframework.orm.jpa.JpaObjectRetrievalFailureException"
message:"Unable to find org.crossfit.app.domain.Booking with id 4101; nested exception is javax.persistence.EntityNotFoundException: Unable to find org.crossfit.app.domain.Booking with id 4101"
path:"/private/planning"
status:500
timestamp:1480070409835

Quand on clique sur les flèches pour changer de jour ça fonctionne (2 jours avant ou 2 jours après)

**Comment by lgangloff** [comment]
Dupplicate #29
