### ISSUE TITLE
[booking] Réservation de créneau impossible avec plusieurs abonnements

### ISSUE THREAD

**Issue by guillaumecolin** [lgangloff/crossfit-2.0#6]
Impossible de réserver quand on a plusieurs abonnements valables

![image](https://cloud.githubusercontent.com/assets/11442517/18944731/620af27e-8627-11e6-93ef-247fcd1195bf.png)

**Comment by lgangloff** [comment]
Problème présent que sur mobile

**Comment by guillaumecolin** [comment]
Je n'ai pas testé sur mobile, testé sur PC avec Chrome

**Comment by lgangloff** [comment]
En version 53.0 pc, pas de problème.
En version 53.0 mobile, j'ai le problème.

Tu peux me dire si la console remonte des infos ?
Sinon, je changerai le processus de sélection de l'abonnement.

**Comment by guillaumecolin** [comment]
C'est ok sur pc, effectivement j'ai le problème sur mobile.
Comment voit on la version déployée ?

**Comment by lgangloff** [comment]
/api/version pour voir la version déployée
