### ISSUE TITLE
[admin] Le nombre de jours affichés a l'air aléatoire

### ISSUE THREAD

**Issue by guillaumecolin** [lgangloff/crossfit-2.0#7]
Quand je clique sur les flèches précédent ou suivant je n'ai pas toujours le même nombre de jours affichés. 

![image](https://cloud.githubusercontent.com/assets/11442517/18945029/cb2daeee-8628-11e6-887f-7c83bccb2cbd.png)

![image](https://cloud.githubusercontent.com/assets/11442517/18945054/eb5e45f2-8628-11e6-90d8-a0839554a2b2.png)

**Comment by lgangloff** [comment]
C'est parce qu'il n'y a pas de créneau le samedi 1er octobre.

**Comment by guillaumecolin** [comment]
Si.
![image](https://cloud.githubusercontent.com/assets/11442517/18947494/92d0c01c-8633-11e6-934f-2197a383ac56.png)

**Comment by lgangloff** [comment]
Alors le jeudi 29 septembre, il n'y pas de créneau ?
