### ISSUE TITLE
[admin] Impossible de supprimer un abonnement

### ISSUE THREAD

**Issue by guillaumecolin** [lgangloff/crossfit-2.0#8]
Impossible de supprimer un abonnement quand il y a des réservations.
Revoir le message d'erreur ?

![image](https://cloud.githubusercontent.com/assets/11442517/18945382/9cfc16bc-862a-11e6-9dd5-203e29771026.png)

**Comment by lgangloff** [comment]
Le bouton de suppression est grisé s'il y a des résas.
A coté de chaque souscription, est affiché le nombre de réservation effectuée
