### ISSUE TITLE
[booking] Mot de passe retrouvé ?

### ISSUE THREAD

**Issue by guillaumecolin** [lgangloff/crossfit-2.0#9]
A quoi sert le lien "Mot de passe retrouvé ?"
Si c'est pour retourner à l'écran de login autant mettre un bouton "retour", non ?

![image](https://cloud.githubusercontent.com/assets/11442517/18946146/e96710b2-862d-11e6-8cb5-95859084a9fe.png)

**Comment by lgangloff** [comment]
Puisque le cerveau peut (sans raison) "oublier" son mot de passe, j'imagine qu'il peut aussi (sans raison toujours) le "retrouver" !
Bref, je trouve ça drôle.

**Comment by crazy-max** [comment]
Mouarf moi ça m'plait xD

**Comment by guillaumecolin** [comment]
Dans ce cas là il faut mettre un point d'exclamation ;)
